export const CHANGING_SEARCH_INPUT_VALUE = 'CHANGING_SEARCH_INPUT_VALUE';
export const CHANGING_SEARCH_BY_VALUE = 'CHANGING_SEARCH_BY_VALUE';
export const SUBMIT_SEARCH_FORM = 'SUBMIT_SEARCH_FORM';

export const CHANGING_SORT_VALUE = 'CHANGING_SORT_VALUE';

export const SHOWING_ONE_CARD_CONTENT = 'SHOWING_ONE_CARD_CONTENT';
export const SHOWING_SEARCH_FILTER_CONTENT = 'SHOWING_SEARCH_FILTER_CONTENT';